import React, { useState, useEffect, useRef } from 'react';
import SvgIcon from './SvgIcon';
import { apiFetch } from '../api';

export default function ChatView({ t, currentLanguage, addToast }) {
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState("");
  const [loading, setLoading] = useState(false);
  const [sessionStats, setSessionStats] = useState({ messages: 0, queries: 0, model: "Local Classifier" });
  const messagesEndRef = useRef(null);

  // Persist session ID in localStorage so chat survives refresh
  const [sessionId, setSessionId] = useState(() => {
    try {
      const key = 'railai_session';
      const existing = localStorage.getItem(key);
      if (existing) return existing;
      const ns = 'sess_' + Math.random().toString(36).slice(2, 11);
      localStorage.setItem(key, ns);
      return ns;
    } catch (e) {
      return 'sess_' + Math.random().toString(36).slice(2, 11);
    }
  });

  const fetchHistory = async () => {
    try {
      const data = await apiFetch(`/api/chat/history/${sessionId}`);
      setMessages(data.messages);
      updateStats(data.messages);
    } catch (err) {
      console.error("Error loading chat history:", err);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, [sessionId, currentLanguage]);

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const updateStats = (msgs) => {
    const userMsgs = msgs.filter(m => m.role === 'user').length;
    setSessionStats({
      messages: msgs.length,
      queries: userMsgs,
      model: "Local RF/LR Pipeline"
    });
  };

  const sendMessage = async (textToSend) => {
    const msg = textToSend || inputValue.trim();
    if (!msg || loading) return;

    if (!textToSend) setInputValue("");
    
    // Add user message locally first
    const updatedMessages = [...messages, { role: 'user', content: msg }];
    setMessages(updatedMessages);
    updateStats(updatedMessages);
    setLoading(true);

    try {

      console.log("SENDING REQUEST TO BACKEND");
      const data = await apiFetch('/api/chat/message', {
        method: 'POST',
        body: JSON.stringify({ session_id: sessionId, message: msg, language: currentLanguage })
      });

      const newMsgs = [...updatedMessages, { role: 'assistant', content: data.reply }];
      setMessages(newMsgs);
      updateStats(newMsgs);

      if ('speechSynthesis' in window) {
        const utterance = new SpeechSynthesisUtterance(data.reply);

        utterance.lang =
          currentLanguage === 'hi'
            ? 'hi-IN'
            : currentLanguage === 'mr'
            ? 'mr-IN'
            : 'en-IN';

        utterance.rate = 1;
        utterance.pitch = 1;

        window.speechSynthesis.speak(utterance);
      }
      
      if (data.slots_filled && data.ticket_id) {
        addToast('success', `${t.newTicket} ${data.ticket_id} ${t.autoGenerated}!`);
      }
    } catch (err) {
      console.error("Error sending message:", err);
      setMessages(prev => [...prev, { role: 'assistant', content: "⚠️ Connection error. Please make sure the backend is running." }]);
    } finally {
      setLoading(false);
    }
  };

  const handleClear = async () => {
    try {
      await apiFetch('/api/chat/clear', { method: 'POST', body: JSON.stringify({ session_id: sessionId, language: currentLanguage }) });
      fetchHistory();
      addToast('info', 'Chat history cleared');
    } catch (err) {
      console.error("Error clearing chat:", err);
    }
  };

  const startVoiceInput = () => {
  if (!('webkitSpeechRecognition' in window)) {
    alert('Speech recognition is not supported in this browser.');
    return;
  }

  const recognition = new window.webkitSpeechRecognition();

  recognition.lang =
    currentLanguage === 'hi'
      ? 'hi-IN'
      : currentLanguage === 'mr'
      ? 'mr-IN'
      : 'en-IN';

  recognition.interimResults = false;
  recognition.maxAlternatives = 1;

  recognition.onresult = (event) => {
    const transcript = event.results[0][0].transcript;
    setInputValue(transcript);
  };

  recognition.start();
};

  const suggestions = [
    t.all === 'All' ? "Show me open critical tickets for today" : "मला आजचे महत्त्वाचे तिकिटे दाखवा",
    t.all === 'All' ? "What's the refund policy for cancelled trains?" : "तिकीट रद्द करण्याचे नियम काय आहेत?",
    t.all === 'All' ? "Lost luggage support ticket please" : "माझे सामान हरवले आहे तक्रार नोंदवा",
    t.all === 'All' ? "I want to file a catering complaint" : "जेवणाची तक्रार नोंदवा"
  ];

  return (
    <div id="page-ai" className="page active" style={{ flexDirection: 'row', height: '100%', overflow: 'hidden', display: 'flex' }}>
      
      {/* Chat Conversation */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        
        {/* Chat header */}
        <div style={{ padding: '14px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: '12px', flexShrink: 0 }}>
          <div style={{ width: '36px', height: '36px', borderRadius: '10px', background: 'linear-gradient(135deg,#F59E0B,#8B5CF6)', display: 'flex', alignItems: 'center', justifyItems: 'center', justifyContent: 'center' }}>
            <SvgIcon name="bot" size={18} color="#fff" />
          </div>
          <div>
            <div style={{ fontWeight: 600, fontSize: '14px' }}>{t.assistantTitle}</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginTop: '2px' }}>
              <span style={{ display: 'inline-block', width: '7px', height: '7px', borderRadius: '50%', background: 'var(--green)', animation: 'pulse 2s infinite', boxShadow: '0 0 6px var(--green)' }}></span>
              <span style={{ fontSize: '11px', color: 'var(--green)' }}>{t.online}</span>
              <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>· scikit-learn offline</span>
            </div>
          </div>
          <div style={{ marginLeft: 'auto', display: 'flex', gap: '8px', alignItems: 'center' }}>
            <button className="btn-icon" onClick={handleClear} title={t.clearSession}>
              <SvgIcon name="refresh" size={15} />
            </button>
          </div>
        </div>

        {/* Messages Window */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {messages.map((msg, i) => {
            const isUser = msg.role === 'user';
            
            // Format bold text markdown and break lines
            const formatContent = (content) => {
              const withBold = content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
              return { __html: withBold.replace(/\n/g, '<br>') };
            };

            return (
              <div key={i} className="fade-in" style={{ display: 'flex', flexDirection: 'column', alignItems: isUser ? 'flex-end' : 'flex-start', gap: '6px' }}>
                {!isUser && (
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginLeft: '4px' }}>
                    <div style={{ width: '20px', height: '20px', borderRadius: '6px', background: 'linear-gradient(135deg,#F59E0B,#8B5CF6)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <SvgIcon name="zap" size={11} color="#fff" />
                    </div>
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>RailAI</span>
                  </div>
                )}
                <div 
                  className={isUser ? 'chat-bubble-user' : 'chat-bubble-ai'}
                  dangerouslySetInnerHTML={formatContent(msg.content)}
                />
              </div>
            );
          })}

          {loading && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '6px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginLeft: '4px' }}>
                <div style={{ width: '20px', height: '20px', borderRadius: '6px', background: 'linear-gradient(135deg,#F59E0B,#8B5CF6)' }}></div>
                <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>RailAI is thinking...</span>
              </div>
              <div className="chat-bubble-ai" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <span className="typing-dot"></span>
                <span className="typing-dot"></span>
                <span className="typing-dot"></span>
              </div>
            </div>
          )}
          
          <div ref={messagesEndRef} />
        </div>

        {/* Suggestions chips */}
        {messages.length <= 1 && !loading && (
          <div style={{ padding: '0 20px 12px', display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
            {suggestions.map((s, i) => (
              <button
                key={i}
                onClick={() => sendMessage(s)}
                style={{
                  background: 'var(--surface-high)',
                  border: '1px solid var(--border)',
                  borderRadius: '20px',
                  padding: '6px 14px',
                  color: 'var(--text-muted)',
                  fontSize: '12px',
                  cursor: 'pointer',
                  transition: 'all .2s',
                  fontFamily: 'inherit'
                }}
                onMouseOver={(e) => { e.target.style.borderColor = '#F59E0B66'; e.target.style.color = 'var(--text)'; }}
                onMouseOut={(e) => { e.target.style.borderColor = 'var(--border)'; e.target.style.color = 'var(--text-muted)'; }}
              >
                {s}
              </button>
            ))}
          </div>
        )}

        {/* Input box */}
        <div style={{ padding: '12px 20px', borderTop: '1px solid var(--border)', display: 'flex', gap: '10px', alignItems: 'flex-end', flexShrink: 0 }}>
          <textarea
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                sendMessage();
              }
            }}
            className="input-field"
            placeholder={t.chatPlaceholder}
            rows={2}
            style={{ resize: 'none', lineHeight: 1.6, padding: '12px' }}
          />
         <button
  onClick={startVoiceInput}
  style={{
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid var(--border)',
    background: 'var(--surface-high)',
    cursor: 'pointer',
    flexShrink: 0
  }}
>
  🎤
</button>

<button onClick={() => sendMessage()} disabled={loading} className="btn-primary" style={{ padding: '10px 16px', flexShrink: 0 }}>
  <SvgIcon name="zap" size={15} />
  {t.send}
</button>
        </div>

      </div>

      {/* Right panel panel info */}
      <div style={{ width: '280px', borderLeft: '1px solid var(--border)', padding: '20px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '20px', flexShrink: 0 }}>
        <div>
          <div style={{ fontSize: '11px', textTransform: 'uppercase', letterSpacing: '.07em', color: 'var(--text-muted)', marginBottom: '12px', fontWeight: 600 }}>
            {t.aiCapabilities}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            {[
              { icon: 'ticket', label: 'Ticket Analysis', desc: 'Classify & prioritize tickets', color: '#F59E0B' },
              { icon: 'train', label: 'Schedule Insights', desc: 'Delay patterns & predictions', color: '#3B82F6' },
              { icon: 'map', label: 'Route Intelligence', desc: 'Route-wise issue mapping', color: '#10B981' },
              { icon: 'zap', label: 'Auto-Resolution', desc: 'AI-suggested solutions', color: '#8B5CF6' }
            ].map((c, i) => (
              <div key={i} style={{ display: 'flex', gap: '10px', alignItems: 'flex-start', padding: '10px 0', borderBottom: '1px solid var(--border)' }}>
                <div style={{ width: '28px', height: '28px', borderRadius: '8px', background: `${c.color}22`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <SvgIcon name={c.icon} size={14} color={c.color} />
                </div>
                <div>
                  <div style={{ fontSize: '12px', fontWeight: 600 }}>{c.label}</div>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '2px' }}>{c.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div>
          <div style={{ fontSize: '11px', textTransform: 'uppercase', letterSpacing: '.07em', color: 'var(--text-muted)', marginBottom: '12px', fontWeight: 600 }}>
            {t.sessionStats}
          </div>
          <div>
            {[
              { label: t.messages, value: sessionStats.messages },
              { label: t.queriesHandled, value: sessionStats.queries },
              { label: t.model, value: sessionStats.model }
            ].map((s, i) => (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '7px 0', borderBottom: '1px solid #1A2B4740' }}>
                <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>{s.label}</span>
                <span style={{ fontSize: '12px', fontWeight: 600 }}>{s.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
      
    </div>
  );
}
